
export const GET_PLANS_COMPLETED = "GET_PLANS_COMPLETED";
export const GET_PLANS_COMPLETED_WITH_ERROR = "GET_PLANS_COMPLETED_WITH_ERROR";
export const SET_PLAN_COMPLETED = "SET_PLAN_COMPLETED";
export const SET_PLAN_COMPLETED_WITH_ERROR = "SET_PLAN_COMPLETED";
export const SET_ADDON_COMPLETED = "SET_ADDON_COMPLETED";
export const SET_ADDON_COMPLETED_WITH_ERROR = "SET_ADDON_COMPLETED_WITH_ERROR";

const initialState = {};



